#!/usr/bin/env bash

set -eu

for Line in $(cat versions)
do
    mkdir -p $Line
    cd $Line
    if [[ -f "git-revision" ]]; then
        rm git-revision
    fi
    wget "https://channels.nixos.org/${Line}/git-revision"
    version=$(cat git-revision)
    if [[ ! -f "${version}.json.br" ]]; then
        "$1/versions" $version
    fi
    rm git-revision
    cd ..
done
