#!/usr/bin/env bash

set -eu

for Line in $(cat versions); do
  mkdir -p $Line
  cd $Line
  if [[ -f "history" ]]; then
    rm history
  fi
  wget "https://git.oss.uzinfocom.uz/xinux/monitor/raw/branch/main/data/${Line}/history"
  for version in $(cat history | rev | cut -c12- | rev | tail -300); do
    if [[ ! -f "${version}.json.br" ]]; then
      "$1/versions" $version
    fi
  done
  rm history
  cd ..
done
