#!/usr/bin/env bash

set -eu

for Line in $(cat versions)
do
    mkdir -p $Line
    cd $Line
    if [[ -f "history" ]]; then
        rm history
    fi
    wget "https://raw.githubusercontent.com/xinux-org/monitor/main/data/${Line}/history"
    for version in $(cat history | rev | cut -c12- | rev | tail -300)
    do
        if [[ ! -f "${version}.json.br" ]]; then
            "$1/versions" $version
        fi
    done
    rm history
    cd ..
done
