name: "Generate package versions"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: testing

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update files
        working-directory: ./data
        run: nix run

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version data ${{ github.event.repository.updated_at}}
          commit_user_email: buckle_scouts3y@icloud.com
          commit_author: Xinux Manager <buckle_scouts3y@icloud.com>
